import js from "@eslint/js";
import vue from "eslint-plugin-vue";
import vueParser from "vue-eslint-parser";
import prettierRecommended from "eslint-plugin-prettier/recommended";
import globals from "globals";
// Flat-config block (languageOptions.globals) for WXT's build-time auto-imports
// (defineBackground, defineContentScript, ...). Generated by `wxt prepare`,
// which runs on postinstall - so it exists after `npm ci`, before lint.
import wxtAutoImports from "./.wxt/eslint-auto-imports.mjs";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // Global ignores
  {
    ignores: [
      ".output/",
      ".wxt/",
      "node_modules/",
      "dist/",
      "artifacts/",
      "safari/",
    ],
  },

  // JS recommended
  js.configs.recommended,

  // Vue 3 essential (matches legacy plugin:vue/vue3-essential)
  ...vue.configs["flat/essential"],

  // TypeScript recommended - sets @typescript-eslint/parser globally
  ...tseslint.configs.recommended,

  // Restore vue-eslint-parser for Vue SFCs (tseslint overrides parser globally).
  // tseslint.parser is passed as the inner parser for <script lang="ts"> blocks.
  {
    files: ["**/*.vue"],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tseslint.parser,
      },
    },
  },

  // Prettier (disables conflicting formatting rules + runs prettier as a rule)
  prettierRecommended,

  // WXT auto-import globals
  wxtAutoImports,

  // Project-wide settings
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.browser,
        ...globals.webextensions,
      },
    },
    rules: {
      "no-console": process.env.NODE_ENV === "production" ? "warn" : "off",
      "no-debugger": process.env.NODE_ENV === "production" ? "warn" : "off",
      "vue/multi-word-component-names": "off",
      "vue/no-reserved-component-names": "off",
      "@typescript-eslint/no-explicit-any": "warn",
      // Vue Options API legitimately uses const self = this in non-arrow callbacks
      "@typescript-eslint/no-this-alias": "warn",
    },
  },
);
