#!/bin/sh

#  pre-build.sh
#  IITC-Button
#
#  Created by Lucka on 6/10/2021.
#  

cd "${PROJECT_DIR}"

basePath=$(dirname "$0")
PACKAGE_VERSION=$(sed -n 's/^.*version": "\(.*\)",$/\1/p' $basePath/../../package.json)

GIT_COMMIT_COUNT=$(git rev-list --count HEAD || echo '1')

INFO_PLIST_PREPROCESS_FILE="Shared/info-plist-preprocessor.h"

echo "//---------------------------------------------------------------"    >  $INFO_PLIST_PREPROCESS_FILE
echo "// Automatically generated by pre-build.sh. Do NOT edit manually."    >> $INFO_PLIST_PREPROCESS_FILE
echo "//---------------------------------------------------------------"    >> $INFO_PLIST_PREPROCESS_FILE
echo ""                                                                     >> $INFO_PLIST_PREPROCESS_FILE
echo "#define PACKAGE_VERSION ${PACKAGE_VERSION}"                           >> $INFO_PLIST_PREPROCESS_FILE
echo "#define GIT_COMMIT_COUNT ${GIT_COMMIT_COUNT}"                         >> $INFO_PLIST_PREPROCESS_FILE
