name: Build IITC Button

# read-only repo token
# no access to secrets
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '!.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Linter
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Get version from package.json
        if: ${{ github.event.workflow_run.event == 'push' }}
        uses: polyseam/get-version-from-package-json@v.1.0.0
        id: get-version-from-package-json
        with:
          path-to-file: './package.json'

      - name: Save metadata for push event
        if: ${{ github.event.workflow_run.event == 'push' && !startsWith(github.ref, 'refs/tags/v') }}
        run: |
          mkdir -p ./build/.metadata
          mv artifacts/*.zip ./build/iitc-button-${{github.sha}}.zip
          echo "beta" > ./build/.metadata/build_type
          echo ${{ github.sha }} > ./artifact/.metadata/commit
          echo $( ls ./artifacts/ | grep '.zip' ) > ./build/.metadata/zip_filename

      - name: Save metadata for release event
        if: ${{ github.event.workflow_run.event == 'push' && startsWith(github.ref, 'refs/tags/v') }}
        run: |
          mkdir -p ./build/.metadata
          mv artifacts/*.zip ./build/iitc-button-${{steps.get-version-from-package-json.outputs.version}}.zip
          echo "release" > ./build/.metadata/build_type
          echo ${{ github.sha }} > ./artifact/.metadata/commit
          echo $( ls ./artifacts/ | grep '.zip' ) > ./build/.metadata/zip_filename

      - name: Save metadata for pull_request event
        if: ${{ github.event.workflow_run.event == 'pull_request' }}
        run: |
          mkdir -p ./build/.metadata
          mv artifacts/*.zip ./build/iitc-button-${{github.event.pull_request.head.sha}}.zip
          echo "PR" > ./build/.metadata/build_type
          echo ${{ github.event.pull_request.head.sha }} > ./artifact/.metadata/commit
          echo $( ls ./artifacts/ | grep '.zip' ) > ./build/.metadata/zip_filename

      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "./build/iitc-button-${{ steps.get-version-from-package-json.outputs.version }}/*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
            ./build/.metadata/
            ./build/build/
