name: Build IITC Button

# read-only repo token
# no access to secrets
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '!.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Linter
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Get version from package.json
        if: startsWith(github.ref, 'refs/tags/v')
        uses: polyseam/get-version-from-package-json@1.0.0
        id: get-version-from-package-json
        with:
          path-to-package-json: './package.json'

      - name: Save metadata
        run: |
          mkdir -p ./build/.metadata
          if [ "$GITHUB_EVENT_NAME" = "push" ]; then
            if [[ "$GITHUB_REF" =~ ^refs/tags/ ]]; then
              mv artifacts/*.zip ./build/iitc-button-${{steps.get-version-from-package-json.outputs.version}}.zip
              echo "release" > ./build/.metadata/build_type
            else
              # Beta build from master branch
              mv artifacts/*.zip ./build/iitc-button-${{github.sha}}.zip
              echo "beta" > ./build/.metadata/build_type
            fi
            echo ${{ github.sha }} > ./build/.metadata/commit
          elif [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            mv artifacts/*.zip ./build/iitc-button-${{github.event.pull_request.head.sha}}.zip
            echo "PR" > ./build/.metadata/build_type
            echo ${{ github.event.pull_request.head.sha }} > ./build/.metadata/commit
          fi
          echo $( ls ./build/ | grep '.zip' ) > ./build/.metadata/zip_filename
          echo "GITHUB_SHA_SHORT=$(cat ./build/.metadata/commit | cut -c 1-6)" >> $GITHUB_ENV

      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: "./build/iitc-button-${{ steps.get-version-from-package-json.outputs.version }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: iitc-button-${{ env.GITHUB_SHA_SHORT }}-artifact
          path: |
            ./build/
